### ISSUE TITLE
Conflict with Multipliers Scraps / Value

### ISSUE THREAD

**Issue by DHStyle541** [stormytuna/HellWeather#2] opened 2024-01-26 04:08 UTC
Hi, This is mod have conflict with Multipliers Scraps / Value when Landing.
because when Scan only 400, maybe Make Priority if Landing Hell The Multipliers Scraps / Value is Eclipse
(I Testing using WeatherMultipliers and MeteoMultiplier)

![image](https://github.com/stormytuna/HellWeather/assets/154591650/0f3032d1-31ad-4e70-b373-382feda0d3a9)

![image](https://github.com/stormytuna/HellWeather/assets/154591650/9cd6c4fc-1981-478b-85e9-485079fe245d)

*Edit
Suggest add config the Multipliers Scrap / Value for Hell Weather

*Edit agins
get Softlock if Landing Custom Moons

**Comment by stormytuna** [comment] 2024-02-05 16:59
I don't plan on adding manual cross compatibility on this mod's side. Modded weathers are lacking an API currently to make it easy to allow for cross compatibility easier, if this happens in the future feel free to reopen and I will reinvestigate this

Second edit is a duplicate of #3

**Closed as not planned by stormytuna** 2024-02-05 16:59 UTC
